apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-mq
  labels:
    app: rabbitmq
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: ampq-rabbit-mq
          ports:
            - containerPort: 5672
          image: rabbitmq:3-management
