apiVersion: v1
kind: Service
metadata:
  name: rabbit-mq-service
spec:
  selector:
    app: rabbitmq
  type: NodePort
  ports:
    - port: 5672
      name: http
      targetPort: 5672
      protocol: TCP