apiVersion: v1
kind: Service
metadata:
  name: test-ai-backend-service
spec:
  selector:
    app: testai
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http